/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

import "sst"
declare module "sst" {
  export interface Resource {
    "Auth": {
      "publicKey": string
      "type": "sst.cloudflare.Auth"
      "url": string
    }
    "CloudflareAccountID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CloudflareApiToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "EmailAPIKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "EmailApi": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "Marketing": {
      "type": "sst.cloudflare.StaticSite"
      "url": string
    }
    "MyDatabaseId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MyEmail": {
      "configSet": string
      "sender": string
      "type": "sst.aws.Email"
    }
    "TurnstileSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "game": {
      "type": "sst.cloudflare.StaticSite"
      "url": string
    }
  }
}
// cloudflare 
import * as cloudflare from "@cloudflare/workers-types";
declare module "sst" {
  export interface Resource {
    "AuthAuthenticator": cloudflare.Service
    "AuthStorage": cloudflare.KVNamespace
    "DonegeonDB": cloudflare.D1Database
    "Worker": cloudflare.Service
  }
}

import "sst"
export {}