DROP TABLE IF EXISTS idempotency_keys;
DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS task_labels;
DROP TABLE IF EXISTS tasks;
DROP TABLE IF EXISTS labels;
DROP TABLE IF EXISTS sections;
DROP TABLE IF EXISTS projects;
